Vivid/Vivid/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r"^$",views.HomePage.as_view(), name='home'),
    url(r"^thanks/$", views.ThanksPage.as_view(), name='thanks'),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r'^dashboard/',include('dashboard.urls')),
    url(r'^excel/',include('excel.urls')),
    url(r'^base_todo/',include('base_todo.urls')),
    path('', include('cal.urls')),
]

Vivid/accounts/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'login/$',auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    url(r'logout/$',auth_views.LogoutView.as_view(),name='logout'),
    url(r'signup/$',views.SignUp.as_view(),name='signup'),
    path('edit_profile/',views.edit_profile,name='edit_profile'),
]

Vivid/cal/urls.py
from django.conf.urls import url
from . import views

app_name = 'cal'
urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    url(r'^event/new/$', views.event, name='event_new'),
	url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
]

Vivid/dashboard/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
urlpatterns = [
    path('', views.base_dash, name='base_dash'),
]

Vivid/dashboard/models.py
from django.db import models
from django.contrib.auth import get_user_model
from accounts.models import User
# Create your models here.

User = get_user_model()

Vivid/dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,redirect
import datetime
# Create your views here.

@login_required
def base_dash(request):
    return render(request, 'dashboard/base_dash.html')

Vivid/dashboard/templates/dashboard/base_dash.html
{% load staticfiles %}
<!DOCTYPE html>

<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Title Page-->
    <title>Vivid Vision</title>

    <!-- Fontfaces CSS-->
    <link href="{% static "css/font-face.css" %}" rel="stylesheet" media="all">
    <link href="{% static "vendor/font-awesome-4.7/css/font-awesome.min.css" %}" rel="stylesheet" media="all">
    <link href="{% static "vendor/font-awesome-5/css/fontawesome-all.min.css" %}" rel="stylesheet" media="all">
    <link href="{% static "vendor/mdi-font/css/material-design-iconic-font.min.css" %}" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="{% static "vendor/bootstrap-4.1/bootstrap.min.css" %}" rel="stylesheet" media="all">

    <!-- Vendor CSS-->
    <link href="{% static "vendor/animsition/animsition.min.css" %}" rel="stylesheet" media="all">
    <link href="{% static "vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" %}" rel="stylesheet" media="all">
    <link href="{% static "vendor/wow/animate.css" %}" rel="stylesheet" media="all">
    <link href="{% static "vendor/css-hamburgers/hamburgers.min.css" %}" rel="stylesheet" media="all">
    <link href="{% static "vendor/slick/slick.css" %}" rel="stylesheet" media="all">
    <link href="{% static "vendor/select2/select2.min.css" %}" rel="stylesheet" media="all">
    <link href="{% static "vendor/perfect-scrollbar/perfect-scrollbar.css" %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static "css/theme.css" %}" rel="stylesheet" media="all">

</head>

<body class="animsition">
    <div class="page-wrapper pb-0">
        <!-- HEADER MOBILE-->
        <header class="header-mobile d-block d-lg-none">
            <div class="header-mobile__bar">
                <div class="container-fluid">
                    <div class="header-mobile-inner">
                        <a class="logo" href="{% url 'base_dash' %}">
                          Vivid Vision
                        </a>
                        <button class="hamburger hamburger--slider" type="button">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                        </button>
                    </div>
                </div>
            </div>
            <nav class="navbar-mobile">
                <div class="container-fluid">
                    <ul class="navbar-mobile__list list-unstyled">
                        <li>
                            <a href="{% url 'base_dash' %}">
                            <i class="fas fa-tachometer-alt"></i>Dashboard</a>
                        </li>
                        <li>
                            <a href="{% url 'accounts:edit_profile' %}">
                            <i class="fas fa-user"></i>Profile</a>
                        </li>
                        <li>
                            <a href="{% url 'todo' %}">
                                <i class="fas fa-chart-bar"></i>Todo List</a>
                        </li>
                        <li>
                            <a href="{% url 'index_excel' %}">
                                <i class="fas fa-table"></i>Tables</a>
                        </li>
                        <li>
                            <a href="{% url 'cal:calendar' %}">
                                <i class="fas fa-calendar-alt"></i>Calendar</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- END HEADER MOBILE-->

        <!-- MENU SIDEBAR-->
        <aside class="menu-sidebar d-none d-lg-block">
            <div class="logo">
                <a href="{% url 'base_dash' %}">
                  <h2 class="text-primary text-center">Vivid Vision</h2>
                </a>
            </div>
            <div class="menu-sidebar__content js-scrollbar1">
                <nav class="navbar-sidebar">
                    <ul class="list-unstyled navbar__list">
                        <li>
                          <a href="{% url 'base_dash' %}">
                            <i class="fas fa-tachometer-alt"></i>Dashboard
                          </a>
                        </li>
                        <li>
                            <a href="{% url 'accounts:edit_profile' %}">
                            <i class="fas fa-user"></i>Profile</a>
                        </li>
                        <li>
                          <a href="{% url 'todo' %}">
                            <i class="fas fa-tasks"></i>Todo List
                          </a>
                        </li>
                        <li>
                          <a href="{% url 'index_excel' %}">
                            <i class="fas fa-table"></i>Tables
                          </a>
                        </li>
                        <li>
                          <a href="{% url 'cal:calendar' %}">
                            <i class="fas fa-calendar-alt"></i>Calendar
                          </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </aside>
        <!-- END MENU SIDEBAR-->

        <!-- PAGE CONTAINER-->
        <div class="page-container">
            <!-- HEADER DESKTOP-->
            <header class="header-desktop">
                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        <div class="header-wrap">
                            <div class="header-button ml-auto">
                                <div class="account-wrap">
                                    <div class="account-item clearfix js-item-menu">
                                        <div class="image">
                                            <img src="{% static 'img/1.png' %}" alt="User" />
                                        </div>
                                        <div class="content">
                                            <a class="js-acc-btn" href="#">{{user.username}}</a>
                                        </div>
                                        <div class="account-dropdown js-dropdown">
                                            <div class="info clearfix">
                                                <div class="image">
                                                    <a href="#">
                                                        <img src="{% static 'img/1.png' %}" alt="John Doe" />
                                                    </a>
                                                </div>
                                                <div class="content">
                                                    <h5 class="name">
                                                        <a href="#">{{user.username}}</a>
                                                    </h5>
                                                    <span class="email">{{user.email}}</span>
                                                </div>
                                            </div>
                                            <div class="account-dropdown__body">
                                                <div class="account-dropdown__item">
                                                    <a href="{% url 'accounts:edit_profile' %}">
                                                        <i class="zmdi zmdi-account"></i>Account</a>
                                                </div>
                                            </div>
                                            <div class="account-dropdown__footer">
                                                <a href="{% url 'accounts:logout' %}">
                                                    <i class="zmdi zmdi-power"></i>Logout</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- HEADER DESKTOP-->

            <!-- MAIN CONTENT-->
            <div class="main-content">
              {% block dash_block %}


              {% endblock %}
            </div>
            <!-- END MAIN CONTENT-->
        </div>
    </div>

    <!-- Jquery JS-->
    <script src="{% static "vendor/jquery-3.2.1.min.js" %}"></script>
    <!-- Bootstrap JS-->
    <script src="{% static "vendor/bootstrap-4.1/popper.min.js" %}"></script>
    <script src="{% static "vendor/bootstrap-4.1/bootstrap.min.js" %}"></script>
    <!-- Vendor JS       -->
    <script src="{% static "vendor/slick/slick.min.js" %}">
    </script>
    <script src="{% static "vendor/wow/wow.min.js" %}"></script>
    <script src="{% static "vendor/animsition/animsition.min.js" %}"></script>
    <script src="{% static "vendor/bootstrap-progressbar/bootstrap-progressbar.min.js" %}">
    </script>
    <script src="{% static "vendor/counter-up/jquery.waypoints.min.js" %}"></script>
    <script src="{% static "vendor/counter-up/jquery.counterup.min.js" %}">
    </script>
    <script src="{% static "vendor/circle-progress/circle-progress.min.js" %}"></script>
    <script src="{% static "vendor/perfect-scrollbar/perfect-scrollbar.js" %}"></script>
    <script src="{% static "vendor/chartjs/Chart.bundle.min.js" %}"></script>
    <script src="{% static "vendor/select2/select2.min.js" %}">
    </script>

    <!-- Main JS-->
    <script src="{% static "js/main.js" %}"></script>

</body>

</html>
<!-- end document-->

Vivid/dashboard/templates/dashboard/calendar.html
{% extends 'dashboard/base_dash.html' %}
{% load staticfiles %}
  {% block dash_block %}
    <link rel="stylesheet" href="{% static 'css/style_cal.css' %}">
    <link rel="stylesheet" href="{% static 'css/vanilla-calendar-min.css' %}">
    <!-- FullCalendar -->
    <div class="section__content section__content--p30">
      <div class="container-fluid">
        <div class="row">
          <div class="col">
            <div class="au-card">
              <div id="myCalendar" class="container-fluid vanilla-calendar" style="margin-bottom: 20px"></div>
            </div>
          </div><!-- .col -->
        </div>
      </div>
    </div>
    <!-- full calendar requires moment along jquery which is included above -->
    <script src="{% static 'js/vanilla-calendar-min.js' %}"></script>
    <script>
        let pastDates = true

        let calendar = new VanillaCalendar({
            selector: "#myCalendar",
            months: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
            shortWeekday: ['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat'],
            onSelect: (data, elem) => {
                console.log(data, elem)
            }
        })
    </script>


{% endblock %}